server {
    listen 9513 ssl;
    server_name 10.10.142.96 localhost;

    ssl_certificate /etc/ssl/certs/selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/selfsigned.key;

    location /api/ {
        rewrite ^/api(/.*)$ $1 break;
        proxy_pass http://localhost:9515;
    }

    location / {
        proxy_pass http://localhost:9514;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
